### ISSUE TITLE
get_all_info results in TypeError

### ISSUE THREAD

**Issue by Shkev** [williamgilpin/pypdb#12]
The get_all_info method results in a TypeError when the get_info method returns None. The code is attempting to access the result of the get_info method as a dictionary, which is not possible when its value is None.
This can probably be fixes with some simple exception handling code.

**Comment by williamgilpin** [comment]
Hi @Shkev, thank you very much for finding this issue!

Would you mind posting a snippet that triggers this error? I tried putting random strings of characters into `get_all_info` and it didn't trigger the exception, and so I'm guessing that this is due to how the database is structured for certain types of pdb entries

**Comment by williamgilpin** [comment]
(apologies, I closed this in error)

**Comment by Shkev** [comment]
Hi @williamgilpin,
the code I ran was the following
`proteins = pypdb.Query("SARS-CoV-2").search()`
`proteins = [get_all_info(p) for p in proteins]`
and it produced a TypeError saying that Nonetype object is not subscriptable. I was able to fix it using an exception handler.

I does seem a bit weird though that it did not produce an error for random strings, so, like you said, it may have just been due to the structure of the database.

**Comment by williamgilpin** [comment]
@Shkev It looks like you are hitting the rate limit on the RCSB API. I haven't figured out an easy way to build-in rate limits, but one hack is to add a manual wait time between requests.

In future releases, I'll see if it's possible to bundle requests. It's not obvious to me whether this is possible with the REST API, but it might be possible if we move to the new GraphQL API

```
import time 

proteins = Query("SARS-CoV-2").search()
protein_info = list()
for pdb in proteins:
    try:
        protein_info.append(get_all_info(pdb))
    except:
        print(pdb)
    time.sleep(.1)

```

**Comment by williamgilpin** [comment]
@Shkev I just took a crack at fixing the API rate limit issue internally. Please update your code to the latest GitHub version, and try running your code. You should get a warning that it's waiting between requests, but it should work. Let me know if it does not.

**Comment by Shkev** [comment]
@williamgilpin Yes it looks like it works now!
