### ISSUE TITLE
ETA on new release?

### ISSUE THREAD

**Issue by jaimergp** [williamgilpin/pypdb#15]
Hi! We are super excited about the new rate limited requests! Any chance you have an estimated date for the new release? 1.300 is a year old now! Thanks!

**Comment by williamgilpin** [comment]
Hi @jaimergp just checking---the rate limiting should be live in the development version

`pip install git+git://github.com/williamgilpin/pypdb`

Are you using the PyPI version? I'm happy to put a new release on PyPI, but I wanted to double check that you aren't already using the GitHub version (which may mean that the rate limiting is broken)

**Comment by jaimergp** [comment]
Hi! Thanks for the quick reply! We are using the release on Conda Forge, which should be equivalent to PyPI's.

**Comment by williamgilpin** [comment]
Hi @jaimergp I updated the PyPI release. For now I would just recommend using pip

    pip install pypdb

I was not able to figure out how to update the version on conda-forge

**Comment by williamgilpin** [comment]
@jaimergp I think I got the conda-forge version updated; please let me know if you run into any issues. Thanks!

**Comment by jaimergp** [comment]
Wow, that was fast! Thanks so much! I will try with the new version now and report back if needed!

**Comment by williamgilpin** [comment]
Hi, I'm closing this for now, but please feel free to re-open if I broke anything! 
Thanks, and all the best -william

**Comment by jaimergp** [comment]
Oops, yes, forgot to report back. No news is good news, right? :) Everything is working as expected, thanks again!
