### ISSUE TITLE
get_all_info isn't working

### ISSUE THREAD

**Issue by ynskoroglu** [williamgilpin/pypdb#16]
Hello I've been using this module for about 4 months and I'm running a monthly script to scrap coronavirus-related data. I hadn't have any problems before but get_all_info function gives Type Error without any reason.

Here is the error:
![resim](https://user-images.githubusercontent.com/37922796/98468137-26af0400-21ea-11eb-9df7-0f846f85d49a.png)

I'm also using the latest version. (1.310)
![resim](https://user-images.githubusercontent.com/37922796/98468172-480ff000-21ea-11eb-901b-79b92088655a.png)

**Comment by williamgilpin** [comment]
Hi, thank you very much for the issue. It looks like they discontinued the API, so I'm going to need to refactor the project. Just a heads up that this might take quite some time to fix.

**Comment by williamgilpin** [comment]
Actually, RCSB say that they are not shutting down the API until December 8, and so this might just be a server issue on their end.

**Comment by AURELIEN-MOUMBOCK** [comment]
It seems the old API has already been superseded by the new one, this month. https://www.rcsb.org/news?year=2020&article=5eb18ccfd62245129947212a&feature=true

**Comment by williamgilpin** [comment]
Thank you. It's regrettable, since [this page](https://search.rcsb.org/index.html#search-api) made it appear that I had more time, but perhaps they decided to shut it down earlier.

**Comment by ynskoroglu** [comment]
Hey man, thanks for the response and explanation. I wold like to thank you for putting a lot of work on this module, it was best PDB mining/scrapping tool available and helped a lot during our COVID-realated research.  Working with XML or JSON is tricky so it means a lot to many researchers to have tools like this to make our process easier.  Good news we collected enough data, so hopefully this interception will not effect our research too much. 

Wish you success in your current and future projects. Take your time and stay cool.

**Comment by williamgilpin** [comment]
@ynskoroglu no problem, I do think I will have a slightly messy out today on GitHub, but the API changes will have be breaking changes, unfortunately, and not everything will be available initially. But since right now nothing works at all, I think that an incomplete update will be better than nothing.
