### ISSUE TITLE
Can't Retrieve PDB Release Date

### ISSUE THREAD

**Issue by dbiner0** [williamgilpin/pypdb#19]
pypdb.describe_pdb('5JHL').get('release_date') returns a None value.

**Comment by williamgilpin** [comment]
Hi dbiner, thanks for the issue. RCSB just deprecated the API we were using, which has shuffled everything around. 

Please update to the latest GitHub version, and use the new syntax `get_info('5JHL')['rcsb_accession_info']['initial_release_date']`

My apologies for the change, but the new RCSB API required some adjustments. Thanks

**Comment by dbiner0** [comment]
Hi William,

Thanks for the heads up! It works great with the new syntax.

DB

**Comment by williamgilpin** [comment]
Closing this for now, but please feel free to re-open if any issues pop up.
