### ISSUE TITLE
Trouble with the function get_blast

### ISSUE THREAD

**Issue by Levi-Magny** [williamgilpin/pypdb#26]
Hello!
I'm trying to use the function get_blast() for getting a fasta file from the pdb site. But the following error is showing:
"name 'get_blast' is not defined".
How could I fix that?
My os is Ubuntu 18.04.
Thank you!!!

**Comment by lacoperon** [comment]
This is an issue with the RPDB API changing and us not having reimplemented the BLAST search yet.

I actually was planning on implementing this today/tomorrow, so I'll add this and then you should be able to use it.
(I'll comment when this is done).

**Comment by Levi-Magny** [comment]
OK!! Thank you very much.

**Comment by lacoperon** [comment]
Cool, so [this pull request](https://github.com/williamgilpin/pypdb/pull/27) should implement the functionality you need to search for structures associated with a FASTA file.

(it'll return whatever `ReturnType` you've specified).

Hopefully this helps! You can probably download the FASTA / PDB files from that entity using `get_pdb_file` in `pypyb.py`, if that's what you're trying to do.

Cheers!

**Comment by Levi-Magny** [comment]
Thank you for your support!
Could you help me writing the following code using the _get_pdb_file_:

`blast_results = get_blast(molecula, chain_id=vetorcadeias[i])
just_hits = blast_results['BlastOutput_iterations']['Iteration']['Iteration_hits']['Hit']`

We didn't find a way to implement this with that function.

**Comment by lacoperon** [comment]
Heya, no worries.

So, the way to perform BLAST-like searches has changed slightly with the new API.
You'll want to use the `perform_search` within the new `search_client` I wrote.

## Example Implementation

```
from pypdb.clients.search.search_client import perform_search, RequestOptions
from pypdb.clients.search.search_client import SearchService, ReturnType
from pypdb.clients.search.operators.sequence_operators import SequenceOperator
from pypdb.clients.search.operators.sequence_operators import SequenceType

results = perform_search(
    search_service=SearchService.SEQUENCE,
    return_type=ReturnType.ENTRY,
    search_operator=SequenceOperator(
        sequence_type=SequenceType.PROTEIN,
        sequence=(
          "SMVNSFSGYLKLTDNVYIKNADIVEEAKKVKPTVVVNAANVYLKHGGGVAGALNKATNNAMQVESDDY"
          "IATNGPLKVGGSCVLSGHNLAKHCLHVVGPNVNKGEDIQLLKSAYENFNQHEVLLAPLLSAGIFGADP"
          "IHSLRVCVDTVRTNVYLAVFDKNLYDKLVSSFL"),
        identity_cutoff=0.99,
        evalue_cutoff=1000
      ),
    return_with_scores=True
```

That will return you the PDB entry codes (like "5JUP" or "X427" or whatever), associated with the scores for the match.
You might want to tune `identity_cutoff` or `evalue_cutoff` depending on your use case.

The result returned looks like:
```
[ScoredResult(entity_id='5RV6', score=1.0), ScoredResult(entity_id='5RUT', score=1.0), ScoredResult(entity_id='5RV5', score=1.0), ScoredResult(entity_id='5RV8', score=1.0), ScoredResult(entity_id='5RUW', score=1.0), ScoredResult(entity_id='5RV7', score=1.0), ScoredResult(entity_id='5RUV', score=1.0), ScoredResult(entity_id='5RUI', score=1.0), ScoredResult(entity_id='7KQO', score=1.0), ScoredResult(entity_id='5RUH', score=1.0), ScoredResult(entity_id='7KQP', score=1.0), ScoredResult(entity_id='5RUK', score=1.0),
...
etc.
```

You can also modulate the type of sequence you're searching by changing the `SequenceType` (to, for example, `DNA` or `RNA`).

## On searching via PDB ID

There's currently no way to do this from a PDB ID with the new API, because I haven't yet implemented a `get_fasta` function using the new API.

So, you'll want to look up the sequence manually, and then plug that sequence into the `perform_search` example above.
(you can even get this from a URL, for example: `https://www.rcsb.org/fasta/entry/5JUP`).

If you're doing this often for arbitrary PDB entry IDs, I can implement a convenience `get_fasta` function somewhere if that's helpful and necessary. Let me know!

**Comment by Levi-Magny** [comment]
Got it!
I actually need to search for the fasta file from a PDB ID, I'm using this search quite often for arbitrary PDB IDs.
So it'll really be helpful if you can implement the `get_fasta` function.
Thank you again!

**Comment by lacoperon** [comment]
So, [this pull request](https://github.com/williamgilpin/pypdb/pull/29), once merged, should implement the functionality you want.

Once it's implemented, all the logic you'll need is implemented in:
`pypdb/clients/fasta/fasta_client.py`
`pypdb/clients/search/search_client.py`
`pypdb/clients/search/operators/sequence_operators.py`
(let me know if any parts are confusing -- ideally this is clear and useable)

## Example usage 
(let me know if this doesn't satisfy your use case :) )

```
from pypdb.clients.fasta.fasta_client import get_fasta_from_rcsb_entry
from pypdb.clients.search.search_client import perform_search
from pypdb.clients.search.search_client import SearchService, ReturnType
from pypdb.clients.search.operators.sequence_operators import SequenceOperator
# Fetches the first sequence in the "6TML" fasta file (arbitrary)
fasta_sequence = get_fasta_from_rcsb_entry("6TML")["6TML_1"].sequence
# Performs sequence search ('BLAST'-like) using the FASTA sequence
results = perform_search(
    search_service=SearchService.SEQUENCE,
    return_type=ReturnType.ENTRY,
    search_operator=SequenceOperator(
        sequence=fasta_sequence,
        identity_cutoff=0.99,
        evalue_cutoff=1000
        # note that the `sequence_type` is autoresolved here, but this won't work for ambiguous
        # sequences like "AAAAAA" (you'll want to handle the raised exception if need be)
      ),
    return_with_scores=True
)
```

Notably you can also iterate over all fasta sequences in the fasta dict returned by `get_fasta_from_rcsb_entry`.
(to do conditional searches, for example)

Example:
```
for fasta_sequence in get_fasta_from_rcsb_entry("6TML").values():
    print(fasta_sequence)
```

**Comment by Levi-Magny** [comment]
Great!!! You helped me a lot. Now I'm getting the fasta files correctly.
Thanks so much! Happy Holidays.

**Comment by lacoperon** [comment]
C
