### ISSUE TITLE
Trouble with executing sample codes from section "New API for advanced search"

### ISSUE THREAD

**Issue by marketapavlikova** [williamgilpin/pypdb#43]
Dear William,

I'm glad, that I discovered your package PyPDB! It seems to be really useful for me as a Bioinformatician. 
I tried some of the sample codes and I encountered an error, while trying this sample code bellow. Is it because of the new API or is there a mistake on my side? 
(The sample codes from the first section "Search functions that return lists of PDB IDs" work fine for me. I am using pypdb 2.0.)

Code:

![image](https://user-images.githubusercontent.com/72798099/125928276-1b561fd8-a78f-4df6-b0b8-04eee63bfc37.png)

Error:

![image](https://user-images.githubusercontent.com/72798099/125928133-e3693fc8-bee7-4e2b-a84a-99b0b1b2fba5.png)

Thank you very much in advance.
Best regards,

Marketa Pavlikova

**Comment by williamgilpin** [comment]
Hello, I don't think that we have PolymerEntity implemented yet, unfortunately. I can try to take a look at this later this month

**Comment by williamgilpin** [comment]
Hello, I don't think that we have PolymerEntity implemented yet, unfortunately. I can try to take a look at this later this month

**Comment by williamgilpin** [comment]
@marketapavlikova Hello, I can confirm that this is working on my end. Please check to see if you have the latest version. Thanks very much for using the repo; I hope it is helpful for your research
