### ISSUE TITLE
Cannot perform the first query from the jupyter notebook

### ISSUE THREAD

**Issue by YannRoussel** [williamgilpin/pypdb#46]
Hello,

I am trying to run the demos jupyter notebook and I get an error when running the second cell:
`found_pdbs = Query("ribosome").search()`
`print(found_pdbs[:10])`

I get:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-53b8e7e3615e> in <module>
----> 1 found_pdbs = Query("ribosome").search()
      2 print(found_pdbs[:10])

~/anaconda3/lib/python3.7/site-packages/pypdb/pypdb.py in search(self, num_attempts, sleep_time)
    251          data=query_text)
    252 
--> 253         if response.status_code == 200:
    254             pass
    255         else:

AttributeError: 'NoneType' object has no attribute 'status_code'
```

Any idea where the issue could come from?
Thanks you.

**Comment by williamgilpin** [comment]
Hi @YannRoussel thank you for this report! I will check this today and get back to you.

**Comment by williamgilpin** [comment]
This looks like a breaking change in the RCSB API.  For now, I would recommend seeing if the [raw JSON search page](https://search.rcsb.org/#building-search-request) can get you the results you need.

If you do manage to get this working, I would appreciate any information---I have not been able to figure this out

**Comment by williamgilpin** [comment]
Hi @YannRoussel the latest GitHub version fixes this, thanks to @samuelstanton for the fix!
