### ISSUE TITLE
Chemical description retrieval / new RCSB API

### ISSUE THREAD

**Issue by zrqiao** [williamgilpin/pypdb#50]
Dear pypdb developers,

I am looking for an operation that retrieves non-polymer molecule information (chemical name, InChI, etc.) given a pdb code query. I noticed that the describe_chemical has been commented out, and [this RCSB page](https://www.rcsb.org/docs/programmatic-access/migrating-from-legacy-apis) shows that the API for web retrieval has been deprecated. 

I am wondering if new open-source tools have been developed to adapt to these changes. If this is an unsolved issue, I am willing to contribute new functionalities to this repository. Thanks.

**Comment by williamgilpin** [comment]
Hi @zrqiao if you are willing to contribute, I would very much appreciate your help with fixing this. Ever since the API change last year, I've been having trouble staying on top of bugs---so any help would very much be appreciated

**Comment by zrqiao** [comment]
Thank you @williamgilpin for the information! I'll start to make some modifications and create a PR when it's in a good shape.

**Comment by williamgilpin** [comment]
Hello, does the latest PR #55 solve your issue?

**Comment by zrqiao** [comment]
@williamgilpin I think so, thank you for pinging me! Sorry I have eventually moved to another project and abandoned works on this...
