### ISSUE TITLE
RCSB Search API V1 has been removed

### ISSUE THREAD

**Issue by noahharrison64** [williamgilpin/pypdb#52]
Ran into an issue searching with database today - noticed that this module queries V1 API which was [removed yesterday](https://www.rcsb.org/news/feature/625041e8c8eabd0c4864f205) and replaced by V2. Looks like the module here needs to be updated to reflect this

**Comment by williamgilpin** [comment]
Closing this issue for now, although please re-open it if any compatibility issues arise.
