### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by chuliangcui** [williamgilpin/pypdb#54]
Hi, recently we got the "AttributeError: 'NoneType' object has no attribute 'status_code'" error for everything in our data, which worked before.
I tested with the demo code in pydpb and the same error showed up.
`found_pdbs = Query(27499440, "PubmedIdQuery").search()
print(found_pdbs[:10])`
Can you have a look?
Thanks!

**Comment by williamgilpin** [comment]
Uh oh sounds like a server side change, I will investigate it

**Comment by williamgilpin** [comment]
Hi @chuliangcui your prompt is working on my computer. Can you check your version and dependencies?

**Comment by chuliangcui** [comment]
> 

It works now! Thanks for the fast help!
