### ISSUE TITLE
get_pdb_file leads to broken link 

### ISSUE THREAD

**Issue by gustalima** [williamgilpin/pypdb#8]
Hi, the function to download a given pdb file fails as the result from (the generic link in the examples)
http://www.rcsb.org/pdb/download/downloadFile.do?fileFormat=structfact&structureId=2F5N
now leads to an Error page. 

I'm using Python 3.6.

Cheers,

**Comment by williamgilpin** [comment]
Hello and thank you for the report. This looks like an API change on the RCSB's end. I will investigate to see what we are supposed to use for the new API.

**Comment by williamgilpin** [comment]
Hi @gustalima I just released a new version that should fix your issue.

**Comment by gustalima** [comment]
Hi @williamgilpin, I updated and it works great now! Thanks for the (very) quick fix.
