### ISSUE TITLE
do_search gives bad pdbid's when using MotifQuery search

### ISSUE THREAD

**Issue by GMC1997** [williamgilpin/pypdb#9]
Whenever I try to run this example:

>>> search_dict = make_query('T[AG]AGGY',querytype='MotifQuery')
>>> found_pdbs = do_search(search_dict)
>>> print(found_pdbs)

Instead of this:
['3LEZ', '3SGH', '4F47']

I get really broken id's like this:
['EZ:1', '3SGH:1', '4F47:1']

Same thing happens when I try a different sequence.

**Comment by williamgilpin** [comment]
Thank you for the report, this sounds like an API change that I will need to fix. Does this issue occur with other functions that retrieve PDB IDs, or just this one?

**Comment by GMC1997** [comment]
Thanks for the reply, from what I've seen, it just happens when I use querytype='MotifQuery'.

**Comment by GMC1997** [comment]
Any chance you might fix this issue anytime soon? I need a PDB ID searcher that searches via sequence for a project. If not, then are you aware of any modules or packages that do the same thing? I've been searching everywhere and this one and ProDy are the only ones I could find, but ProDy keeps constantly failing to connect.

**Comment by williamgilpin** [comment]
Hello, I have identified that the source of the issue is line 217 of `pypdb.py`. I agree that this needs revision:

> idlist[0] = idlist[0][-4:]

I am working on fixing this without breaking other functionality, presumably by splitting using regex.

**Comment by williamgilpin** [comment]
Hi @GMC1997, please try the latest GitHub version, to see if that solves your problem. Cheers.
